version: '3.7'
services:
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    networks: 
      - redis
    restart: unless-stopped
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  redis:
  postgres:
volumes:
  postgres: